### ISSUE TITLE
Error in rep(value, length.out = nrows) : 

### ISSUE THREAD

**Issue by peachone** [WWXkenmo/ENIGMA#1]
**attempt to replicate an object of type 'S4'**
Thank you so much for uploading such a great tool, but I'm having problems using a as a reference.
I managed to common Create ENIGMA object, but got an error when running the mode batch effect correction.

 It seems that I have a problem with my reference, but my reference is a single cell data of 7 cell types.Here is my code situation, I would be grateful if you could help me .

> 
> ##### mode batch effect correction
> ```
> +   egm = batch_correct(egm, 
> +                       varname_cell_type = "cellType", 
> +                       n_pseudo_bulk=100)
> ```
> Tue Sep 28 11:28:58 2021 Reference is from Single Cell RNA-seq, doing batch correction in S mode. 
> Tue Sep 28 11:28:58 2021 Generating pseudo bulk... 
> Tue Sep 28 11:29:24 2021 Doing ComBat... 
> Found 693 genes with uniform expression within a single batch (all zeros); these will not be adjusted for batch.
> Found2batches
> Adjusting for0covariate(s) or covariate level(s)
> Standardizing Data across genes
> Fitting L/S model and finding priors
> Finding parametric adjustments
> Adjusting the Data
> 
> Tue Sep 28 11:29:27 2021 Restore reference... 
> Error in rep(value, length.out = nrows) : 
>   attempt to replicate an object of type 'S4'

**Comment by WWXkenmo** [comment]
Thx for using our tool! I would check the source code later
I just want to maker sure that are you using the v1.1 version or just originally version, I gonna check later

**Comment by peachone** [comment]
@WWXkenmo Thanks for the reply, I've re-run it now and it's ok.

**Comment by WWXkenmo** [comment]
Okey! I really want hear the feedback from the user, if you encounter any questions about usage and analytic results interpretation, contact with me please!
