### ISSUE TITLE
Related CTS-DE Analysis

### ISSUE THREAD

**Issue by mybioinformatics** [WWXkenmo/ENIGMA#12]
Dear Developer 

Hello, thank you for developing a great algorithm. 

Using the algorithm you developed, I deconvolved the bulk RNA sequencing data I have to find pseudo - cell type specific genes. 

Example ) DEG = FindCSE_DEG(egm,y,FoldChange=TRUE)

But I have a question here. 

If I arbitrarily apply a log2 to the "FoldChange" value that comes out as a result, making it in the form of log2(FoldChange), is it safe to assume that it is the same as the log2FC value that we usually get when we analyze with Deseq2 or limma or EdgeR ? 

If the arbitrarily applied log2 is the same as the log2FC values we get from a typical Bulk RNA DEG, then I would like to go further and use these values to do GSEA analysis etc. 

Thanks for reading this long post :)

**Comment by WWXkenmo** [comment]
Hey,

Sorry for this super late response after more than one yyyyyears!

I think you can safely apply on it, but I will say its not directly correspond to the value like other method, for example, limma

But still you can go further and use these values to do GSEA analysis, that definately doable, just go ahead.

It might be toooo late to say this but happy to see what outcome it is.

Many thanks!
Weixu
